# Generated by Django 4.2.6 on 2024-10-16 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size_million', models.FloatField()),
                ('total_capital_committed_billion', models.FloatField()),
                ('global_south_deals', models.IntegerField()),
                ('global_south_countries', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('investment_million', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('country_capital_million', models.FloatField()),
                ('theme', models.CharField(max_length=255)),
                ('theme_capital_million', models.FloatField()),
                ('total_emissions', models.FloatField()),
                ('scope_1_emissions', models.FloatField()),
                ('scope_2_emissions', models.FloatField()),
                ('scope_3_emissions', models.FloatField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='funds.fund')),
            ],
        ),
    ]
